命令稿啟動於 2019年03月 3日 上午 02:13:30
]0;/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1
[32mGuan_Lun@Guan_Lun-PC [33m/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1[0m
$ whoami;  pw[K[K[Kpwd
Guan_Lun
/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1
]0;/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1
[32mGuan_Lun@Guan_Lun-PC [33m/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1[0m
$ git config -I
error: unknown switch `I'
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    -t, --type <>         value is given this type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)
    --expiry-date         value is an expiry date

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)
    --default <value>     with --get, use default value when missing entry

]0;/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1
[32mGuan_Lun@Guan_Lun-PC [33m/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1[0m
$ git congi[K[Kfig -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
]0;/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1
[32mGuan_Lun@Guan_Lun-PC [33m/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1[0m
$ git clone https://github.com/MoMoParadox/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1
[32mGuan_Lun@Guan_Lun-PC [33m/cygdrive/c/Users/Guan_Lun/Desktop/School/107-2/C++/lab1[0m
$ exit

命令稿已於 2019年03月 3日 上午 02:15:19
 完成